- name: Playbook SSH-copy-id
  hosts: facility
  become: yes
  gather_facts: no
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Skopiuj klucz publiczny na serwer
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', '~/.ssh/klucz.pub') }}"
